# Generated by Django 5.2 on 2025-04-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(verbose_name="Date of Booking"),
        ),
    ]
