# Generated by Django 5.2 on 2025-05-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0002_alter_booking_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["name"], name="idx_name"),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(fields=["title"], name="idx_title"),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["title", "inventory"], name="idx_title_inventory"
            ),
        ),
    ]
