# Generated by Django 5.2 on 2025-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0003_booking_idx_name_menu_idx_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Party Size"
            ),
            preserve_default=False,
        ),
    ]
