version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    ports:
      - 8008:8000
    environment:
      - DEBUG=0
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    labels:  # new
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`api.little-lemon.xyz`)"
        - "traefik.http.routers.django.tls=true"
        - "traefik.http.routers.django.tls.certresolver=letsencrypt"
  traefik:  # new
      build:
        context: .
        dockerfile: Dockerfile.traefik
      ports:
        - 80:80
        - 443:443
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "./traefik-public-certificates:/certificates"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard-django-traefik.your-domain.com`)"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$28STBSL4$P65.nPZlU.JqCJExnAQdZ1"

volumes:
  traefik-public-certificates:
