
[project]
name = "be-capstone"
version = "0.1.0"
description = "Meta Backend Engineer Capestone Project."
authors = [
    {name = "Terry A. Brooks, Jr."}
]
license = {text = "GNU"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=5.1.7,<6.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "django-prometheus (>=2.3.1,<3.0.0)",
    "drf-extensions (>=0.7.1,<0.8.0)",
    "django-configurations (>=2.5.1,<3.0.0)",
    "cryptography (>=44.0.2,<45.0.0)",
    "pymysql (>=1.1.1,<2.0.0)",
    "drf-redesign (>=0.5.0,<0.6.0)",
    "mysqlclient (>=2.2.7,<3.0.0)"
]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
autoflake = "^2.3.1"
django-debug-toolbar = "^5.1.0"
astroid = "^3.3.9"

