"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

"""

from os import environ as enviornment_var
from pathlib import Path

from configurations import Configuration

BASE_DIR = Path(__file__).resolve().parent.parent


class Base(Configuration):
    SECRET_KEY = enviornment_var["SECRET_KEY"]
    STATIC_URL = "static/"
    ROOT_URLCONF = "config.urls"
    WSGI_APPLICATION = "config.wsgi.application"
    LANGUAGE_CODE = "en-us"
    TIME_ZONE = "UTC"
    USE_I18N = True
    FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
    USE_TZ = True

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [
                f"{BASE_DIR}/templates",
                "/Users/terry-brooks./Github/be_capstone-1/.venv/lib/python3.13/site-packages/django/forms/templates",
            ],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]
    CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
    CRISPY_TEMPLATE_PACK = "bootstrap5"
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": enviornment_var["DATABASE_NAME"],
            "USER": enviornment_var["DATABASE_USER"],
            "PASSWORD": enviornment_var["DATABASE_PASSWORD"],
            "HOST": enviornment_var["DATABASE_HOST"],
            "PORT": enviornment_var["DATABASE_PORT"],
            "OPTIONS": {
                "ssl_mode": "PREFERRED",
                "ssl": {
                    "ca": enviornment_var["DB_CERT_PATH"],  # Optional
                },
            },
        }
    }
    REST_FRAMEWORK = {
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",
        ],
        "DATE_FORMAT": "%m-%d-%Y",
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticatedOrReadOnly",
        ],
        "TIME_FORMAT": "%I:%M %p",
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
        "PAGE_SIZE": 10,
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
            "rest_framework.throttling.UserRateThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {"anon": "20/minute", "user": "30/minute"},
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.TokenAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ],
    }
  
    DJOSER={"USER_ID_FIELD":"username"}
    SPECTACULAR_SETTINGS = {
        "TITLE": "Little Lemon Menu and Booking API",
        "DESCRIPTION": "",
        "VERSION": "1.0.0",
        "SWAGGER_UI_DIST": "SIDECAR",
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR"
,
        "REDOC_DIST": "SIDECAR",
        "SECURITY": [
            {"TokenAuth": []},
        ],
        "AUTHENTICATION_SCHEMES": {
            "TokenAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": 'API Token passed via the Authorization header. Example: "Authorization: Token {token}"',
            },
        },
    }


class Grading(Base):
    DEBUG = False
    ALLOWED_HOSTS = ["little-lemon.xyz"]
    CSRF_TRUSTED_ORIGINST = (
        ["https://localhost", "http://localhost", "https://little-lemon.xyz"],
    )

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "applications.resturant",  # Add this line
        "django_prometheus",
        "drf_redesign",
        "rest_framework",
        "rest_framework.authtoken",
        "django_filters",
        "crispy_forms",
        "crispy_bootstrap5",
        "drf_spectacular",
        "drf_spectacular_sidecar",
        "djoser",
        
    ]

    MIDDLEWARE = [
        "django_prometheus.middleware.PrometheusBeforeMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "django_prometheus.middleware.PrometheusAfterMiddleware",
    ]


class Development(Base):
    DEBUG = True
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINST = (["https://localhost ", "http://localhost"],)

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "crispy_forms",
        "crispy_bootstrap5",
        "django_filters",
        "debug_toolbar",
        "applications.resturant",
        "django_prometheus",
        "drf_redesign",
        "rest_framework",
        "rest_framework.authtoken",
        "drf_spectacular",
        "drf_spectacular_sidecar",
        "djoser",
    ]

    MIDDLEWARE = [
        "django_prometheus.middleware.PrometheusBeforeMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "django_prometheus.middleware.PrometheusAfterMiddleware",
    ]
