# Generated by Django 5.2 on 2025-05-15 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPAllowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        help_text="IP address in IPv4 or IPv6 format",
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for this IP address",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this IP will not be allowed even if in the list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Allow List Entry",
                "verbose_name_plural": "IP Allow List Entries",
                "db_table": "ip_allow_list",
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="ProtectedPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_pattern",
                    models.CharField(
                        help_text="URL pattern to restrict (can use regex patterns)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of what this path protects",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this path will not be IP restricted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Protected Path",
                "verbose_name_plural": "Protected Paths",
                "db_table": "protected_routes",
                "ordering": ["path_pattern"],
            },
        ),
    ]
