name: Codacy Coverage Reporter
on: "push"

permissions:
  contents: read
  pull-requests: write
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v3
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
          final: true
